### ISSUE TITLE
容器内日志如何采集

### ISSUE THREAD

**Issue by liguozhong** [loggie-io/loggie#105]
需要pod的 yaml 需要做特定的 empty 或者 hostpath 的前提才可以采集到吗？ 下面是一个我们的demo yaml

```yaml
volumeMounts:
        - mountPath: /home/admin/logs
          name:01606d0d6354456aa546dfbb36d8a764-datadir
          subPath: logs

  volumes:
    - name:01606d0d6354456aa546dfbb36d8a764-datadir
      persistentVolumeClaim:
        claimName: >-
          01606d0d6354456aa54
```

**Comment by liguozhong** [comment]
是不是 pod 一定得制定 volumes，同时必须value 类型是 emptyDir 和 hostPath 这两类的其中一种才能采集到 容器内的日志。
如果 pod 完全不配置       volumes: 这种pod容器内的日志可以采集到吗

```yaml
      volumes:
      - emptyDir: {}
        name: log     
      volumes:
      - hostPath:
          path: /data/log
          type: ""
```

**Comment by liguozhong** [comment]
源码看起来，pod如果没有配置 volumes 就无法使用采集容器内的日志的。是这样吗？ 是受限的的pod，需要pod 有配置 volumes 才可以采集是吧？

![image](https://user-images.githubusercontent.com/9583245/158760526-dc4efd29-0bbd-4f2b-9775-6e1d2abb7a19.png)

**Comment by liguozhong** [comment]
函数看球来也是一定要判断，empty和 hostpath才可以

![image](https://user-images.githubusercontent.com/9583245/158762105-1644051e-76f4-40ac-8311-aab45f80e154.png)

**Comment by liguozhong** [comment]
比如下面的测试 demo pod，什么volume 都没有配置，能不能使用 [loggie](https://github.com/loggie-io/loggie) 采集到 容器内的日志。

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebiz-deployment
  labels:
    app: ebiz-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ebiz-app
  template:
    metadata:
      labels:
        app: ebiz-app
    spec:
      containers:
        - name: ebiz
          image: docker.io/xdatcloud/demo:latest
```

**Comment by ethfoo** [comment]
pod没有挂载volume的情况下，我们内部版本支持从docker rootfs采集日志，但是需要挂载docker sock，下个小版本，我们考虑使用更好的方案去支持一下。

**Comment by liguozhong** [comment]
另外我们有一些用pvc 挂在的pod，这种日志能采集得了吗？

```yaml
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
        name: cassandra-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: fast
        volumeMode: Filesystem
      status:
        phase: Pending

```
