### ISSUE TITLE
未复现文档中同时采集容器标准输出和容器内日志文件的功能

### ISSUE THREAD

**Issue by LynnTh** [loggie-io/loggie#109]
按照文档所示，进行配置，只能采集标准输出的日志，未能采集容器内日志文件。
采集对象是我写的一个简单的程序，同时向标准输出和文件输出日志内容：
```
kind: Deployment
metadata:
  name: log2file
spec:
  selector:
    matchLabels:
      app: log2file
  template:
    metadata:
      labels:
        app: log2file
    spec:
      containers:
        - name: log2file
          image: reg.harbor.com/logging/log2file:v1.0.0
          env:
            - name: LOG_PATH
              value: /var/log/tw/
          volumeMounts:
          - mountPath: /var/log/tw
            name: log
      volumes:
        - emptyDir: {}
          name: log
```
sink文件：
```
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  name: log2file
spec:
  sink: |
    type: dev
    printEvents: true
```
Interceptor文件：
```
apiVersion: loggie.io/v1beta1
kind: Interceptor
metadata:
  name: log2file
spec:
  interceptors: |
    - type: normalize
      name: stdproc
      belongTo: ["stdoutlog"]
      processors:
      - jsonDecode: ~
      - drop:
          targets: ["stream", "time", "body"]
      - regex:
          target: "log"
          pattern: 'time=\"(?<time>.*?)\" level=(?<level>\S+) msg=\"(?<msg>.*?)\" No=(?<No>\S+)'
      - drop:
          targets: ["log"]
    - type: normalize
      name: fileproc
      belongTo: ["infolog"]
      processors:
      - jsonDecode: ~
```
logconfig文件：
```
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: log2file
  namespace: default
spec:
  selector:
    type: pod
    labelSelector:
      app: log2file
  pipeline:
    sources: |
      - type: file
        name: stdoutlog
        paths:
        - stdout
        fields:
          from: stdout
      - type: file
        name: infolog
        paths:
        - /var/log/tw/info.*.log
        fields:
          from: filelog
    sinkRef: log2file
    interceptorRef: log2file
```
