### ISSUE TITLE
Adding raw sink codec 

### ISSUE THREAD

**Issue by ethfoo** [loggie-io/loggie#136]
Support a kind of sink codec which do nothing but just return event body bytes.

example:

```
    sink:
      type: dev
      printEvents: true
      codec:
        type: raw
```
