### ISSUE TITLE
file sink bug

### ISSUE THREAD

**Issue by lyp256** [loggie-io/loggie#201]
## In what area(s)?
 > /area sink

## What version of Loggie?
v1.1.0
## Expected Behavior

使用 file sink 作为输出，并配置让不同的 log 输出到与之对应的文件中

例如：
```yaml
sink:
      type: file
      workerCount: 1
      baseDirs:
        - ./logs
      filename: /${cluster_name}/${namespace}/${app_kind}/${app_name}/${+YYYYMMDD}.log
      maxSize: 500
      maxAge: 7
      maxBackups: 50
      compress: true
```

## Actual Behavior

log 被随机输出到了不同文件中

## Steps to Reproduce the Problem

稍后我将提供修复 PR
