### ISSUE TITLE
Log collection of container file system

### ISSUE THREAD

**Issue by ethfoo** [loggie-io/loggie#208]
## Describe the feature

Collect the log files in container even if the pod is not mounting any volumes. So Loggie need to find the path in the node via the log files in the container.

### enable
Enable this feature by just set `rootFsCollectionEnabled` to true, see below:
```
  discovery:
    enabled: true
    kubernetes:
      # can be "" or "docker" or "containerd"
      containerRuntime: "docker" 
      rootFsCollectionEnabled: true
```

- When setting the `containerRuntime` field to null, Loggie will get the container runtime by cri.version dynamically which is like `crictl version`.
But we still recommend setting it to a specific value, such as `docker` or `containerd` base on your kubernetes cluster.

### docker runtime
When setting the`containerRuntime` field to `docker`, add volumeMount/volume of Loggie daemonset for docker sock.
```yaml
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
```
```yaml
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersocket
```

In addition，make sure the there is `mountPropagation: HostToContainer` in docker volumeMount:

```yaml
            - mountPath: /var/lib/docker
              mountPropagation: HostToContainer
              name: docker
```

### containerd runtime
When setting the`containerRuntime` field to `containerd`, add volumeMount/volume of Loggie daemonset for containerd sock.
```yaml
        volumeMounts:
        - mountPath: /run/containerd/containerd.sock
          name: containerdsocket
```
```yaml
      volumes:
      - hostPath:
          path: /run/containerd/containerd.sock
          type: ""
        name: containerdsocket
```
Usually the socket path is `/run/containerd/containerd.sock`, which you can also find by checking the kubelet `--container-runtime-endpoint` args.
Don't forget to add `hostPID: true` in template.spec of Loggie daemonset, otherwise Loggie won't be able to read the `/proc/<pid>/root` in the node.
```yaml
spec:
  selector:
    matchLabels:
      app: loggie
  template:
    metadata:
      labels:
        app: loggie
    spec:
      ...
      hostPID: true
      ...
```
