### ISSUE TITLE
多行日志的优化

### ISSUE THREAD

**Issue by shaoyun** [loggie-io/loggie#256]
## Describe the feature

最近我做了一些尝试，为团队提供一种轻量的日志收集解决方案，ELK太重了，最后选型Zinc， 对loggie增加了Zinc的sink，使用过程中发现一些问题。

 1. 通过正则提取java日志的时候，无法将多行日志信息提取到指定字段中，只有在原文body字段中才能看见
 2. 如果我的日志是+8区的日志，通过timestamp转换的时候无法设置from中的字段的时区，最终我不得不做一些改动

改动如下：

pkg/interceptor/normalize/regex.go
```go
type RegexConfig struct {
	Target      string `yaml:"target,omitempty" default:"body"`
	Pattern     string `yaml:"pattern,omitempty" validate:"required"`
	UnderRoot   bool   `yaml:"underRoot,omitempty" default:"true"`
	IgnoreError bool   `yaml:"ignoreError"`
	AppendTo    string `yaml:"appendTo,omitempty" default:""` //增加的字段
}
func (r *RegexProcessor) Process(e api.Event) error {
        // .......
	pl := len(paramsMap)
	if pl == 0 {
		LogErrorWithIgnore(r.config.IgnoreError, "match group with regex %s is empty", r.regex.String())
		log.Debug("regex failed event: %s", e.String())
		return nil
	}

	// 将多行文本第二行开始剩余部分拼接到指定的字段中
	linesRegEx, _ := regexp.Compile(`\n`)
	lines := linesRegEx.Split(string(e.Body()), -1)
	if len(lines) > 1 && r.config.AppendTo != "" {
		lines[0] = paramsMap[r.config.AppendTo]
		paramsMap[r.config.AppendTo] = strings.Join(lines, "\n")
	}

	if r.config.UnderRoot {
		for k, v := range paramsMap {
			header[k] = v
		}
	} else {
		header[SystemLogBody] = paramsMap
	}

	return nil
}
```
pkg/interceptor/normalize/timestamp.go
```go
type TimestampConvert struct {
	From       string `yaml:"from,omitempty" validate:"required"`
	FromLayout string `yaml:"fromLayout,omitempty" validate:"required"`
	FromLocal  bool `yaml:"fromLocal,omitempty" validate:"required"` // 增加的字段，当然能够直接指定时区更好
	ToLayout   string `yaml:"toLayout,omitempty" validate:"required"`
	ToType     string `yaml:"toType,omitempty"`
	local      bool   `yaml:"local,omitempty"`
}

// 防止非UTC时间被转换为UTC时间
if target.FromLocal {
	timeVal, err = time.ParseInLocation(target.FromLayout, timeStr, time.Local)
	if err != nil {
		log.Info("parse time: %s by layout %s error", timeStr, target.FromLayout)
		continue
	}
}
```
以下是我针对springboot日志的配置
```yaml
pipelines:
  - name: local
    sources:
      - type: file
        name: filelog
        paths:
          - /Users/shaoyun/workdir/temp/log/spring.log
        multi:
          active: true
          pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}"
    interceptors:
      - type: normalize
        name: javalog
        belongTo: ["filelog"]
        processors:
          - regex:
              pattern: '(?<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3})\s+(?<level>INFO|WARN|DEBUG|ERROR|TRACE)\s+\d+\s+---\s+\[(?<thread>.+)\]\s+(?<method>\S+)\s+:\s+(?<message>.*)'
              appendTo: 'message'
          - copy:
              convert:
                - from: "time"
                  to: "@timestamp"
          - timestamp:
              convert:
                - from: "@timestamp"
                  fromLayout: "2006-01-02 15:04:05.000"
                  fromLocal: true
                  toLayout: "unix_ms"
          - drop:
              targets: ["body"]
    sink:
      type: zinc
      host: "http://172.30.10.133:4080"
      username: admin
      password: admin
      index: "gears-service-20"
      printEvents: true
      codec:
        pretty: false
```

**Comment by guanbear** [comment]
”对loggie增加了Zinc的sink“，这个赞啊，可以贡献出来吗？ @shaoyun 
 之前我也调研到了zinc，虽然项目还处于很早期，不过感觉很有前景。或者可能等GA以后再支持zinc sink也挺好，看官方说目前可能数据格式还会有变化。

ZincSearch currently has most of its API contracts frozen. It's data format may still experience changes as we improve things. Currently ZincSearch is in beta. Data format should become highly stable when we move to GA (version 1).

**Comment by guanbear** [comment]
哦 我看到了 https://github.com/loggie-io/loggie/pull/254

**Comment by shaoyun** [comment]
k8s中POD日志是JSON格式，控制台输出的日志如果是多行日志，stdout中是多条记录，怎么去匹配呢，有没有处理这种日志场景的考虑 @ethfoo

**Comment by ethfoo** [comment]
> k8s中POD日志是JSON格式，控制台输出的日志如果是多行日志，stdout中是多条记录，怎么去匹配呢，有没有处理这种日志场景的考虑 @ethfoo

这个在v1.2.0已经优化，参考一下文档：https://loggie-io.github.io/docs/user-guide/use-in-kubernetes/collect-container-logs/#_5

**Comment by ethfoo** [comment]
> * 通过正则提取java日志的时候，无法将多行日志信息提取到指定字段中，只有在原文body字段中才能看见

v1.2.0已经支持normalize interceptor里rename body了

**Comment by ethfoo** [comment]
> 2\. 如果我的日志是+8区的日志，通过timestamp转换的时候无法设置from中的字段的时区，最终我不得不做一些改动

这个有兴趣提个PR？增加from和to的时区配置？

**Comment by shaoyun** [comment]
> > * 通过正则提取java日志的时候，无法将多行日志信息提取到指定字段中，只有在原文body字段中才能看见
> 
> v1.2.0已经支持normalize interceptor里rename body了

我的意思是将多行多余的部分追加到正则提取的字段中，而非body或者log字段中的全文，例如如下的message字段中

```yaml
    - regex:
        pattern: '(?<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3})\s+(?<level>INFO|WARN|DEBUG|ERROR|TRACE)\s+\d+\s+---\s+\[(?<thread>.+)\]\s+(?<method>\S+)\s+:\s+(?<message>.*)'
        appendTo: 'message'
````

**Comment by shaoyun** [comment]
> > 2. 如果我的日志是+8区的日志，通过timestamp转换的时候无法设置from中的字段的时区，最终我不得不做一些改动
> 
> 这个有兴趣提个PR？增加from和to的时区配置？

好的，目前我的实现是from增加fromZone配置，to在我的使用场景中没有遇到，我抽空提个PR

```
  - timestamp:
      convert:
        - from: "@timestamp"
          fromLayout: "2006-01-02 15:04:05.000"
          fromZone: "Asia/Shanghai"
          toLayout: "unix_ms"
```
