### ISSUE TITLE
How do I get the fields in the normalize regex?

### ISSUE THREAD

**Issue by laojianzi** [loggie-io/loggie#266]
loggie version: 1.2.0

body: `10.244.0.1 - - [13/Dec/2021:12:40:48 +0000] "GET / HTTP/1.1" 404 683`
```yaml
interceptors:
- type: normalize
  processors:
  - regex:
      pattern: '(?<ip>\S+) (?<id>\S+) (?<u>\S+) (?<time>\[.*?\]) (?<url>\".*?\") (?<status>\S+) (?<size>\S+)'
```

Q: I tried to get `ip` but didn't get
---
I think we should add `e.Fill(e.Meta(), header)` here
https://github.com/loggie-io/loggie/blob/b4c80b06adacd65545f6ca6cc2fa7f79877cc6ea/pkg/interceptor/normalize/regex.go#L101-L110
