### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by zanderme** [loggie-io/loggie#275]
## What version of Loggie?
v1.2.0

## Expected Behavior

不产生panic

## Actual Behavior
panic，导致 loggie POD 重启
```
goroutine 90 [running]:
sync.(*WaitGroup).Add(0xc000aed000, 0xc0065abf00)
	/usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).checkWaitForStopTask(0xc000c8c480)
	/pkg/source/file/watch.go:759 +0x25d
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).maintenance(0xc005097f50)
	/pkg/source/file/watch.go:737 +0x28
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).run(0xc000c8c480)
	/pkg/source/file/watch.go:628 +0x2aa
created by github.com/loggie-io/loggie/pkg/source/file.newWatcher
	/pkg/source/file/watch.go:80 +0x291
```

## Steps to Reproduce the Problem
配置：
```
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  name: kafka
spec:
  sink: |
    type: kafka
    brokers: ["10.10.xxx.xxx:9092"]
    topic: "dev_log_${fields.topic}"

---

apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: error
  namespace: default
spec:
  pipeline:
    sinkRef: kafka
    sources: |
      - type: file
        name: error
        paths:
          - /var/log/service/err/*/log.*
        addonMeta: true
        ignoreOlder: 12h
        workerCount: 128
        fields:
          cluster: dev
          topic: error
  selector:
    type: pod

---

apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: business
  namespace: default
spec:
  pipeline:
    sinkRef: kafka
    sources: |
      - type: file
        name: business
        paths:
          - /var/log/service/business/*/log.*
        addonMeta: true
        ignoreOlder: 12h
        workerCount: 128
        fields:
          cluster: dev
          topic: business
  selector:
    type: pod

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: loggie-config-falcon-loggie
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  loggie.yml: |-
    loggie:
      discovery:
        enabled: true
        kubernetes:
          containerRuntime: docker
          k8sFields:
            agent: loggie
            containerName: ${_k8s.pod.container.name}
            logConfig: ${_k8s.logconfig}
            namespace: ${_k8s.pod.namespace}
            nodeIp: ${_k8s.node.ip}
            nodeName: ${_k8s.node.name}
            podName: ${_k8s.pod.name}
          parseStdout: true
          rootFsCollectionEnabled: true
      http:
        enabled: true
        port: 9196
      monitor:
        listeners:
          filesource: null
          filewatcher: null
          pipeline: null
          queue: null
          reload: null
          sink: null
        logger:
          enabled: true
          period: 30s
      reload:
        enabled: true
        period: 10s

```
