### ISSUE TITLE
cannot rename fields which containing '.'

### ISSUE THREAD

**Issue by listencx** [loggie-io/loggie#295]
```
spec:
  pipeline:
    interceptors: |
      - type: normalize
        processors:
        - add:
            fields:
              log_type: pod-log
        - rename:
            convert:
              - from: "app.kubernetes.io/appname"
                to: "appname"
    sinkRef: loki
    sources: |
      - type: file
        name: stdout
        fieldsUnderRoot: true
        matchFields:
          labelKey: ["app.kubernetes.io/appname"]
        paths:
        - stdout
        
```

log info: move fields from app.kubernetes.io/appname is not exist
