### ISSUE TITLE
Reload optimization of container log collection

### ISSUE THREAD

**Issue by ethfoo** [loggie-io/loggie#333]
## Describe the feature

Currently, Kubernetes discovery in Loggie will automatically render and generate a pipeline, in which the file source includes the specific path (converted from the container path), and at the same time, k8s-related meta information such as podname will be generated as the fields field.
However, when there are many Pods matched by logconfig, a large number of sources files will be generated. When any Pod is rebuilt, the Pipeline configuration will be modified, triggering the reload of the entire Pipeline configuration, and frequent reload will lead to possible log loss.
In other abnormal situations, for example, pods crash and rebuild continuously, which will also lead to frequent reloads.

In order to avoid the above problems, we cannot write fields with kubernetes and paths in the configuration file. For example, the paths field in the current file source records the information of the specific Pod. Whenever the Pod is destroyed, the configuration of the source will change, so that As a result, the entire Pipeline needs to be reloaded.
To solve this problem, we need to aggregate the sources corresponding to multiple Pods matched by a Logconfig on a node into one. Even if any one of the Pods changes, the configuration remains unchanged and no reload occurs. All paths and k8s fields are dynamically changed at runtime.

The actual generated configuration looks like this, no specific paths and kubernetes fields in the file source configruation.
```yaml
  sources:
  - name: demo
    type: file
    codec:
      type: regex
      bodyFields: log
      pattern: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$
    paths:
    - containerLogs
```
