### ISSUE TITLE
failed to send logs to loki with kubernetes pod label which contains "/"

### ISSUE THREAD

**Issue by jinglanghe** [loggie-io/loggie#342]
## What version of Loggie?
1.2.0
## Expected Behavior

send log to loki with k8s pod label which contains "/" successfully

## Actual Behavior

It doesn't work. loggie pod prints error log.

## Steps to Reproduce the Problem
1. I add matchFields.labelKey: ["*"] in sources, and then apply it to kubernetes. The loggie pod status becomes CrashLoopBackOff.
Here is my logConfig yaml
```
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: iam-backend-loki
  namespace: default
spec:
  selector:
    type: pod
    labelSelector:
      app.kubernetes.io/name: iam-backend
  pipeline:
    sources: |
      - type: file
        enabled: true
        fieldsUnderRoot: true
        matchFields:
          labelKey: ["*"]
        name: common
        paths:
          - stdout
```
![Snipaste_2022-08-24_22-34-22](https://user-images.githubusercontent.com/67052947/186446112-aff8c6ca-1b1d-48ee-815d-2708afe6cd8d.jpg)

2. I try to add "contentType: protobuf" to loki sink config. The loggie pod status is Running. But it doen't work, the loggie pod log prints this:
```
2022-08-24 22:05:08 ERR pkg/pipeline/pipeline.go:316 > consumer batch failed: server returned HTTP status 400 Bad Request (400): 1:26: parse error: unexpected character inside braces: '.'
```
![8324b7550c72509d5eee8817f3510e9](https://user-images.githubusercontent.com/67052947/186447317-a5e373fb-87b2-467a-9891-ca90e0ae1bec.png)
