### ISSUE TITLE
sink配置kafka写入topic问题

### ISSUE THREAD

**Issue by carmenlee52** [loggie-io/loggie#404]
## Ask your question here:
请问配置sink 为kafka，kafka配置了auto create topic，loggie在写入kafka时是不会自动创建topic的吗？需要手动创建才能写入
配置如下
apiVersion: loggie.io/v1beta1
```yaml
kind: Sink
metadata:
  creationTimestamp: "2022-11-07T09:23:38Z"
  generation: 5
  name: kafka
  resourceVersion: "49137555"
  uid: 86085072-d28e-484c-974f-71371a8a8594
spec:
  sink: "type: kafka\ntopic: \"huawei_prod_log_${fields._topic_}\"\nbrokers: \n  -
    kafka-0.kafka-headless.default:9092\n  - kafka-1.kafka-headless.default:9092\n
    \ - kafka-2.kafka-headless.default:9092\n
```

**Comment by ethfoo** [comment]
会默认创建topic的，确认一下你这里的${fields._topic_}是否生效？

**Comment by carmenlee52** [comment]
```yaml
$ kubectl get clusterlogconfig.loggie.io/access -o yaml
apiVersion: loggie.io/v1beta1
kind: ClusterLogConfig
metadata:
  name: access
spec:
  pipeline:
    interceptorRef: default
    sinkRef: kafka
    sources: |
      - enabled: true
        excludeFiles:
        - \.gz$
        fields:
          _cluster_: prod
          _log_agent_: loggie
          _topic_: access
        name: access
        paths:
        - /var/log/service/access/**
        type: file
  selector:
    labelSelector:
      app: '*'
    type: pod
```
sink配置
```yaml
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  name: kafka
spec:
  sink: |
    type: kafka 
    brokers:
      - kafka-0.kafka-headless.default:9092
      - kafka-1.kafka-headless.default:9092
      - kafka-2.kafka-headless.default:9092
    topic: "prod_log_${fields._topic_}" 
    parallelism: 4
```
用上面的配置不生效
