### ISSUE TITLE
容器内日志采集，是否有相关示例文档？

### ISSUE THREAD

**Issue by vinsonzou** [loggie-io/loggie#445]
按照官网配置教程，sink配置为kafka，dev，zinc都无法采集到容器内日志？loggie配置没任何报错，不清楚是哪块出问题了。

环境
- k8s: 1.24.3
- containerd: 1.6.4

sink配置
```
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
     name: dev
spec:
    sink: |
       type: dev
       printEvents: true
       codec:
           type: raw
```

interceptor配置
```
apiVersion: loggie.io/v1beta1
kind: Interceptor
metadata:
     name: default
spec:
    interceptors: |
       - type: rateLimit
          qps: 90000
```

日志路径示例如下
```
/app/game/logs/dayreport/dayreport_2023-01-04.log
/app/game/logs/dayreport/dayreport_2023-01-05.log
```

logConfig配置
```
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
     name: game
spec:
    selector:
        type: pod
        labelSecector:
           app: game
    pipeline:
       sources: |
           - type: file
              name: game_dayreport
              fields:
                _log_type_: dayreport
              paths:
                  - /app/game/logs/dayreport/dayreport_*.log
```
