### ISSUE TITLE
k8s 下挂载了docker的目录和kubelet的软连接，会采集重复吗？

### ISSUE THREAD

**Issue by VanLiuZhi** [loggie-io/loggie#518]
请假个问题：我有个疑问，假如我只采集控制台的日志。

docker的控制台日志输出保存到 `/var/lib/docker/containers/{containerId}/{containerId}-json.log`
里面，这个默认目录也是可以改的，有可能某些业务的集群不是统一配置。我在loggie部署的时候，是把这个目录挂载了的

然后还挂载了kubelet的对容器控制台输出文件的一个软连接  `/var/log/pods/<namespace>_<pod_name>_<pod_id>/<container_name>/<num>.log `

我理解kubelet的这个软连接可以一定程度屏蔽容器运行时的配置差异，直接从这边采集就行了

如果部署文件都挂载了，会不会导致控制台日志采集重复？

因为有业务会控制台输出加文件存储，如果2者都被采集了，我想知道loggie是不是有去重机制或者怎么处理这种情况

**Comment by ethfoo** [comment]
不知道你的日志采集配置是什么，正常只需要在logconfig或者clusterlogconfig里的path里填stdout即可，loggie实际会从你说的「kubelet的对容器控制台输出文件的一个软连接」这里去采集，可以看下文档：https://loggie-io.github.io/docs/user-guide/use-in-kubernetes/collect-container-logs/#logconfig

**Comment by VanLiuZhi** [comment]
```
 - name: dockerlogs
          hostPath:
            path: /data/docker
            type: DirectoryOrCreate
```

因为我还配置了这个，这样在 `/data/docker/path/containers/541028e882b63ffdb4b0715d738d66b7b2da434d7a8cbf6a4099f315fbd3705a/xxx.json.log` 是容器控制台输出的日志，不知道会不会重复采集
