### ISSUE TITLE
采集pod的stdout，使用file sink时，模拟容器重启情况，发现日志丢失

### ISSUE THREAD

**Issue by zzzyuan0** [loggie-io/loggie#527]
* 通过 docker kill --signal=HUP eb151e5cec9f60b69 方式让loggie内容器重启/ 或者去容器内部kill掉进程
* 然后去查看日志输出路径的日志，发现中间缺了一部分日志
* clcg 配置
``` yaml
apiVersion: loggie.io/v1beta1
kind: ClusterLogConfig
metadata:
  name: collect-stdout-config
spec:
  selector:
    type: pod
    labelSelector:
       label: log-collect
  pipeline:
    sources: |
      - type: file
        name: stdout-collect
        paths:
        - stdout
    sink: |
      maxBackups: 1
      maxSize: 20
      type: file
      codec:
        type: raw
      filename: /log/today/pods/${fields.namespace}_${fields.podname}_${fields.poduid}/${fields.containername}/stdout.log
```
* values 配置
``` yaml
# 镜像版本
image: "loggieio/loggie:v1.4.0"

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 50Mi

# loggie 额外参数
extraArgs:
  # 开启loggie日志输出至目录
   log.enableFile: true
  # 日志输出目录
   log.directory: /log/today
  # 日志输出文件名
   log.filename: loggie.log
  # 日志是否需要彩色
   log.noColor: true
  # 关闭stdout
   log.enableStdout: false
  # 日志最大备份文件数， 为1 （即日志轮转备份文件数,加上写入的日志文件共2文件）
   log.maxBackups: 1
  # 文件最大大小 20M
   log.maxSize: 20
  #  log.maxAge: 7
  # log.level: debug 日志等级
  # log.jsonFormat: true 日志是否json格式化

# 挂载额外的数据卷
extraVolumeMounts:
  - mountPath: /var/log/pods
    name: podlogs
  - mountPath: /var/lib/docker/containers
    name: dockercontainers
  - mountPath: /var/lib/kubelet/pods
    name: kubelet
# 挂载本机日志统一输出路径
  - mountPath: /log
    name: logdir

# 额外的卷
extraVolumes:
  - hostPath:
      path: /var/log/pods
      type: DirectoryOrCreate
    name: podlogs
  - hostPath:
      path: /var/lib/docker/containers
      type: DirectoryOrCreate
    name: dockercontainers
  - hostPath:
      path: /var/lib/kubelet/pods
      type: DirectoryOrCreate
    name: kubelet
  - hostPath:
      path: /log
      type: DirectoryOrCreate
    name: logdir

# 环境变量
extraEnvs: {}
# 时区
timezone: Asia/Shanghai

nodeSelector: {}
affinity: {}

tolerations:
 - effect: NoExecute
   operator: Exists
 - effect: NoSchedule
   operator: Exists

## 更新策略 onDelete/RollingUpdate
updateStrategy:
  type: RollingUpdate

config:
  loggie:
    reload:
      enabled: true
      period: 10s
    monitor:
      logger:
      listeners:
        filesource:
          period: 10s
        filewatcher:
          period: 5m
        reload:
          period: 10s
        sink:
          period: 10s
        queue:
          period: 10s
        pipeline:
          period: 10s
    discovery:
      enabled: true
      kubernetes:
        containerRuntime: containerd
        rootFsCollectionEnabled: true
        parseStdout: false
        dynamicContainerLog: true
        typePodFields:
          logconfig: "${_k8s.logconfig}"
          namespace: "${_k8s.pod.namespace}"
          nodename: "${_k8s.node.name}"
          podname: "${_k8s.pod.name}"
          poduid: "${_k8s.pod.uid}"
          containername: "${_k8s.pod.container.name}"
    http:
      enabled: true
      port: 9196
# 默认配置
defaults:
  sources:
    - type: file
# 开启ack
      ack:
        enable: true

```
