### ISSUE TITLE
Sink does not support Elasticsearch for https

### ISSUE THREAD

**Issue by PungYoung** [loggie-io/loggie#542]
```yaml
cat << EOF | kubectl apply -f -
apiVersion: loggie.io/v1beta1
kind: Sink
metadata:
  name: default
spec:
  sink: |
    type: elasticsearch
    index: "loggie"
    hosts: ["https://elasticsearch-master.default.svc:9200"]
    schema: "https"
    username: "elastic"
    password: "123456"
    sniff: false
EOF
```
```sh
kubectl logs -f  -n loggie loggie-gj9zk
```
```
2023-05-27 23:09:03 ERR pkg/sink/elasticsearch/elasticsearch.go:87 > start elasticsearch connection fail, err: health check timeout: Head "https://elasticsearch-master.default.svc:9200": x509: certificate signed by unknown authority: no Elasticsearch node available
2023-05-27 23:09:03 ERR pkg/control/controller.go:93 > retry starting pipeline error: start component sink/elasticsearch: health check timeout: Head "https://elasticsearch-master.default.svc:9200": x509: certificate signed by unknown authority: no Elasticsearch node available
```

kibana is OK
