### ISSUE TITLE
Need match function usage example for Interceptor.transformer

### ISSUE THREAD

**Issue by jangrui** [loggie-io/loggie#587]
## How to modify the following configuration

```
    interceptors: |
      - type: transformer
        actions:
          - action: copy(fields.containername, server)
          - action: copy(fields.namespace, _)
          - action: regex(_)
            pattern: \S+-(?<env>\S+)-\S+
          - if: match(body, regex)
            # regex: (\S+) (\S+) (\S+) (\[.*?\]) \"(.*?) (.*?) (.*?)\" (\S+) (\S+) \"(.*?)\" \"(.*?)\" \"(.*?)\"
            regex: (?<ip>\S+) (?<id>\S+) (?<u>\S+) (?<timestamp>\[.*?\]) \"(?<request_method>.*?) (?<url>.*?) (?<http_version>.*?)\" (?<status>\S+) (?<size>\S+) \"(?<referer>.*?)\" \"(?<agent>.*?)\" \"(?<forwarded>.*?)\"
            then:
              - action: regex(body)
                pattern: (?<ip>\S+) (?<id>\S+) (?<u>\S+) (?<timestamp>\[.*?\]) \"(?<request_method>.*?) (?<url>.*?) (?<http_version>.*?)\" (?<status>\S+) (?<size>\S+) \"(?<referer>.*?)\" \"(?<agent>.*?)\" \"(?<forwarded>.*?)\"
              - action: copy(body, message)
            else:
              - action: move(body, message)
```
