### ISSUE TITLE
Support transformer replace action

### ISSUE THREAD

**Issue by dongjiang1989** [loggie-io/loggie#630]
/area interceptor
## Describe the feature

support replace action.  like: `strings.Replace(...)`

like: https://grafana.com/docs/loki/latest/clients/promtail/stages/replace/

```yaml
interceptors:
  - type: transformer
    actions:
      - action: replace(body)
        old: "abc"
        new: "ABC"
      ...
```
input:
```
{
  "body": "2023-09-04T09:21:20.545525544Z DEBUG abc"
}
```

output:
```
{
  "body": "2023-09-04T09:21:20.545525544Z DEBUG ABC"
}
```
