### ISSUE TITLE
可以支持采集非 K8S 容器的 stdout 日志吗？

### ISSUE THREAD

**Issue by cici503-backup** [loggie-io/loggie#656]
我们不是基于 K8S 调度容器的，想采集容器的 stdout 日志，使用以下 yml，采集无效
```
pipelines:
  - name: demo
    sources:
      - type: file
        name: demo
        paths:
          - stdout
```

想确认下，是我的 yml 配置不对还是当前功能不支持？
