### ISSUE TITLE
老版本k8s 创建crd失败

### ISSUE THREAD

**Issue by cyberchao** [loggie-io/loggie#659]
## Ask your question here:

k8s版本：`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`
loggie版本：v1.4.0

安装方式，没有使用helm install，用的生成yaml文件方式
```
helm pull https://github.com/loggie-io/installation/releases/download/v1.4.0/loggie-v1.4.0.tgz && tar xvzf loggie-v1.4.0.tgz
helm template loggie loggie --output-dir manifests
```

直接使用crds.yaml,报错如下

```
unable to recognize "crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

apiVersion: apiextensions.k8s.io/**v1** 修改为 apiVersion: apiextensions.k8s.io/**v1beta1** 后,报错如下
`kubectl apply -f crd.yaml 发生如下报错：error: error validating "crds.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[0]): unknown field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[0]): missing required field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[1]): unknown field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[1]): missing required field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[2]): unknown field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[2]): missing required field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[3]): unknown field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[3]): missing required field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceColumnDefinition]; if you choose to ignore these errors, turn validation off with --validate=false`

请问，该如何解决呢

**Comment by Auggie321** [comment]
也遇到了类似的问题。
k8s v1.15.6 helm2的环境部署 loggie v1.4.0.
宿主机系统
```shell
NAME="BigCloud Enterprise Linux"
VERSION="22.10U2 LTS"
ID="bclinux"
VERSION_ID="22.10U2"
PRETTY_NAME="BigCloud Enterprise Linux For Euler 22.10U2 LTS"
ANSI_COLOR="0;31"
```
这个和宿主机的系统应该没关系的。

https://loggie-io.github.io/docs/main/getting-started/install/kubernetes/#service
基于quick start的部署介绍，无论是否删除 rm loggie/crds/crds.yaml (实测好几次了)
在使用私有定义lgc文件的时候，也会出现 no match kind of logconfig的内容。
```shell
error: unable to recognize "logconfig1.yaml": no matches for kind "LogConfig" in version "loggie.io/v1beta1"
```
```yaml
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: nginx-ingress-ingress-nginx-controller
  namespace: loggie
spec:
  selector:
    type: pod
    labelSelector:
      app.kubernetes.io/component: controller
  pipeline:
    sources: |
      - type: file
        name: nginx-ingress-controller
        paths:
        - stdout
    sink: |
      type: dev
      printEvents: true
      codec:
        type: json
        pretty: true
```
根据之前部署 helm kube-prometheus-stack 的排错印象，这个还是要基于crd.yaml改造兼容。
