### ISSUE TITLE
retry interceptor goroutine blocking

### ISSUE THREAD

**Issue by kytool** [loggie-io/loggie#668]
> /area interceptor

## What version of Loggie?
main

## Steps to Reproduce the Problem
- loggie.yaml
```yaml
loggie:
  defaults:
    interceptors:
      - type: retry
        retryMaxCount: 1
```
- pipelines.yml
```yaml
pipelines:
  - name: local
    sources:
      - type: file
        name: demo
        paths:
          - /xxx/a.log
    sink:
      parallelism: 2
      type: elasticsearch
      index: "my_test"
      hosts: ["localhost:9999"]
```
es填一个错误的地址，模拟es故障，然后不断写日志文件，在写es的代码加time.Sleep(time.Second * 3)更容易重现bug
![image](https://github.com/loggie-io/loggie/assets/98650328/01230a81-18da-4420-8341-20b3821315f1)
