### ISSUE TITLE
dropEvent not commit offset

### ISSUE THREAD

**Issue by kytool** [loggie-io/loggie#672]
## In what area(s)?
> /area interceptor

## What version of Loggie?
main

## Actual Behavior
dropEvent not commit offset

## Steps to Reproduce the Problem
- pipelines.yml
```yaml
pipelines:
  - name: local
    sources:
      - type: file
        name: demo
        paths:
          - xxx.log
    interceptors:
      - type: transformer
        actions:
          - action: print()
          - if: NOT equal(level, DEBUG)
            then:
              - action: dropEvent()
    sink:
      type: dev
      printEvents: true
      codec:
        pretty: true
```
dropEvent后因为没有commit，导致offset不变
如果某个文件每一行都dropEvent，会导致
1. 重启后会重复读 ，虽然不会到sink，但是还是会消耗资源
1. 不知道文件实际上有没有读
