### ISSUE TITLE
cannot find volume mounts by path

### ISSUE THREAD

**Issue by shuoshadow** [loggie-io/loggie#691]
logconfig
```
apiVersion: loggie.io/v1beta1
kind: LogConfig
metadata:
  name: java-log  # 配置名称，需要在当前namespace下保持唯一
  namespace: dev1
spec:
  selector:
    type: pod
    labelSelector:  # 标签选择器，用于过滤采集的目标pod
      app: java
  pipeline:
    sources: |
      - type: file
        addonMeta: true
        name: common
        matchFields:
          labelKey: ["*"]    # 将所有labels收集到日志
        paths:
          - /log/*/*.log    # 日志采集目录
        multi:
         active: true   # 开启多行匹配模式
         pattern: '\[\d+-\d+-\d+\s\d+:\d+:\d+\.\d+]\s.*'  # 行首正则表达式
    sinkRef: kafka-sink   # 发送到该kafka
    interceptorRef: java-interceptor   # 引用日志解析
```

error log:

describe logconfig
```
Sync type pod test-deploy-7875475b8d-j48fj failed: cannot find volume mounts by path: /log/*/*.log
```
